module ToyRobot
  VERSION: String

  class Robot
    DIRECTIONS: Array[String]

    @east: Integer
    @north: Integer
    @direction: String

    def initialize: (?Integer, ?Integer, ?String) -> void

    def move: () -> void
    def move_east: () -> void
    def move_north: () -> void
    def move_south: () -> void
    def move_west: () -> void

    def turn_left: () -> void
    def turn_right: () -> void

    private

    def turn: (:left | :right) -> void
  end
end